version: '3.8'



services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - public
    ports:
      - '8088:8080'
    env_file:
      - app.env

  postgres:
    image: 'postgres:15.1-alpine'
    networks:
      - public
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

networks:
  public:
    driver: bridge


volumes:
  pg-data:
    driver: local